name: CI

# 触发条件：所有分支的 push 和 PR 都会触发
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '25'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 获取当前 commit 的前 7 位短 Hash，并存入环境变量 SHORT_SHA 中
      - name: Get Short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # 构建 Debug 包
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # 重命名 Debug 包
      # github.ref_name: 分支名 (例如 main)
      # github.run_number: Actions 的历史运行编号 (例如 15)
      # env.SHORT_SHA: 刚刚获取的 7 位 commit 标识 (例如 a1b2c3d)
      - name: Rename APK
        run: |
          SAFE_BRANCH_NAME=$(echo "${{ github.ref_name }}" | tr '/' '-')
          mv app/build/outputs/apk/debug/app-debug.apk "app/build/outputs/apk/debug/OneUIX-Debug-${SAFE_BRANCH_NAME}-Run${{ github.run_number }}-${{ env.SHORT_SHA }}.apk"

      # 上传产物
      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          # name: OneUIX-Debug-${{ github.ref_name }}-Run${{ github.run_number }}-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 15
          archive: false
